# Generated by Django 5.1.4 on 2024-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='article_images/'),
        ),
    ]
